---
title: "Homework 12 - Reproducible Reporting"
output:
  html_document:
    number_sections: false
    toc: no
---

> **Due**: 08 December by 11:00 pm
>
> **Weight**: This assignment is worth **4%** of your final grade.
>
> **Purpose, Skills, & Knowledge**: The purposes of this assignment are:
>
> - Be able to manage computational projects for reproducibility, reuse, and collaboration.
> - Use R tools and conventions to document code and analyses and produce reproducible reports.
> - Be able to publish, share materials, and collaborate through the web.
>
> **Assessment**: Each question indicates the % of the assignment grade, summing to 100%. The credit for each question will be assigned as follows:
>
> - 0% for not attempting a response.
> - 50% for attempting the question but with _major_ errors.
> - 75% for attempting the question but with _minor_ errors.
> - 100% for correctly answering the question.
>
> **Rules**: This entire assignment is **SOLO**. You may not work with other classmates, though you may consult instructors for help.

### 1) Staying organized [5%]

Download and use [this template](templates/hw12.zip) for your assignment. Inside the "hw12" folder, open and edit the YAML at the top of the "hw12.Rmd" file.

> This week's main task is simple: **Create a html document of HW 11**.

For this last assignment, all you need to do is convert what you did in HW 11 into a .Rmd file that compiles to a html document. So you're going to repeat the same steps as in HW 11, except this time your result will be a much nicer, well-formatted html page. **If you want, you may choose to work with a different dataset from HW 11, but you may also just use the same dataset and plots from your HW 11 submission.**

### 3) Choose and load some data [5%]

For this assignment, you will need to find a dataset of your choosing and create **three** summary visualizations. To keep things manageable, choose one of the following datasets from the following libraries. Note that to load any of these data frames, all you need to do is install and load the library.

**dplyr**:

- `storms`
- `starwars`

**ggplot2**:

- `diamonds`
- `economics`
- `midwest`
- `mpg`
- `msleep`
- `txhousing`

**dslabs**:

- `gapminder`
- `movielens`
- `murders`
- `stars`

### 4) Inspect your data [10%]

Once you've chosen a data set, open your `hw12.Rmd` file and begin exploring the data (be sure to load the library that contains the dataset at the top of your file). Write some code in code chunks to preview and summarize the data frame using some of the methods we've used in class. You should be able to quickly get an understanding of what variables are included and their nature. Consider the following questions in your exploration (you don't have to write out answers to these questions - just write code to help you answer them by previewing the data in different ways):

- What is the total size of the data frame?
- What type of data is each variable (numeric, character, logical, date)?
- Do any variables have missing values? Why might that be?
- What are the "boundaries" of each period of observation:
    - For numeric variables, what are the min and max values?
    - For character variables, what are the unique values in the variable?
    - For date variables, what time period do the observations in these data frames span?

### 5) Make plots [50%]

Now that you have a basic understanding of the dataset, make some plots to explore the variables in the data and their potential relationships. You may use base R plotting functions or the **ggplot2** library to make your figures, but you must make at least two different types of figures, including:

1. A scatterplot of involving at least two variables.
2. A bar chart involving at least one variable.

You can choose to plot whichever variables you wish, but you must be able to interpret the results of your plot.

### 6) Interpret your plots [15%]

Below the plot code for each of your plots, write a description and interpretation of your plot in a comment. Make sure you address at least the following questions:

1. Describe what variables you are plotting and why.
2. Describe the primary relationship / trend / information you hope the reader will gain from your visualization.

### 7) Compile your RMarkdown document [10%]

When you're done, click the "knit" button to compile your .Rmd file into a html page. Make sure you've used code chunk settings to make the outputs pretty (e.g. nice figure dimensions, no warning messages, etc.).

### 8) Submit your files on Blackboard [5%]

Create a zip file of all files in your R project folder for this assignment and submit the zip file on Blackboard by the due deadline.
