<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Data Analysis 2 - Data Wrangling</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/paper.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<link rel="icon" href="images/favicon.ico">
<script src="https://kit.fontawesome.com/1392a7030f.js" crossorigin="anonymous"></script>
<style type="text/css">

/* Text */

h1 {
  padding-top: 10px;
  padding-bottom: 10px;
  line-height: 60px;
}
h2 {
  padding-top: 10px;
  padding-bottom: 10px;
  line-height: 50px;
}
h3 {
  padding-top: 10px;
  padding-bottom: 10px;
  line-height: 40px;
}
body {
  font-size: 16px;
  line-height: 26px;
}
blockquote {
  background-color: #ecf0f1;
  padding: 20px;
  border-color: #2296f3;
  border-radius: 5px;
}
blockquote h3 {
  margin-top: 0px;
}

/* Images */

img {
  padding-bottom: 10px;
}

/* Tables */

table {
  border-collapse: collapse;
  margin-bottom:10px;
}
thead {
  border-top: solid #DCDCDC;
  border-bottom: solid #DCDCDC;
}
tr.odd {
  background-color: #F8F8F8;
}
tr:first-child {
  border-top: solid #DCDCDC;
}
tr:last-child {
  border-bottom: solid #DCDCDC;
}

</style>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 64px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h2 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h3 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h4 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h5 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h6 {
  padding-top: 69px;
  margin-top: -69px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">P4A - Fall 2020</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="syllabus.html">
    <span class="far fa-map"></span>
     
    Syllabus
  </a>
</li>
<li>
  <a href="schedule.html">
    <span class="far fa-calendar-alt"></span>
     
    Schedule
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-book"></span>
     
    Lessons
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="L0-course-prep.html">0: Course Prep</a>
    </li>
    <li>
      <a href="L1.1-course-introduction.html">1.1: Course Introduction</a>
    </li>
    <li>
      <a href="L1.2-getting-started.html">1.2: Getting Started</a>
    </li>
    <li>
      <a href="L1.3-operations-data-types.html">1.3: Operations &amp; Data Types</a>
    </li>
    <li>
      <a href="L2.1-functions-packages.html">2.1: Functions &amp; Packages</a>
    </li>
    <li>
      <a href="L2.2-turtle-graphics.html">2.2: Turtle Graphics</a>
    </li>
    <li>
      <a href="L3-creating-functions.html">3: Creating functions</a>
    </li>
    <li>
      <a href="L4.1-conditionals.html">4.1: Conditionals</a>
    </li>
    <li>
      <a href="L4.2-testing-debugging.html">4.2: Testing &amp; Debugging</a>
    </li>
    <li>
      <a href="L5-loops.html">5: Loops</a>
    </li>
    <li>
      <a href="L6-vectors.html">6: Vectors</a>
    </li>
    <li>
      <a href="L7-strings.html">7: Strings</a>
    </li>
    <li>
      <a href="L8-python-intro.html">
        <span class="fab fa-python"></span>
         
        8: Introduction to Python
      </a>
    </li>
    <li>
      <a href="L10.1-data-analysis-prelude.html">10.1: Data Analysis Prelude</a>
    </li>
    <li>
      <a href="L10.2-data-frames.html">10.2: Data Frames</a>
    </li>
    <li>
      <a href="L11-data-wrangling.html">11: Data Wrangling</a>
    </li>
    <li>
      <a href="L12-data-visualization.html">12: Data Visualization</a>
    </li>
    <li>
      <a href="L13-python-data-structures.html">
        <span class="fab fa-python"></span>
         
        13: Python Data Structures
      </a>
    </li>
    <li>
      <a href="L14-reproducible-reporting.html">14: Reproducible Reporting</a>
    </li>
    <li>
      <a href="L15-monte-carlo-methods.html">15: Monte Carlo Methods</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-laptop"></span>
     
    Assignments
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="hw1-getting-started.html">HW 1 - Getting Started</a>
    </li>
    <li>
      <a href="hw2-programming-basics.html">HW 2 - Programming Basics</a>
    </li>
    <li>
      <a href="hw3-creating-functions.html">HW 3 - Creating Functions</a>
    </li>
    <li>
      <a href="hw4-conditionals-testing.html">HW 4 - Conditionals &amp; Testing</a>
    </li>
    <li>
      <a href="hw5-loops.html">HW 5 - Loops</a>
    </li>
    <li>
      <a href="hw6-vectors.html">HW 6 - Vectors</a>
    </li>
    <li>
      <a href="hw7-strings.html">HW 7 - Strings</a>
    </li>
    <li>
      <a href="hw8-data-frames.html">HW 8 - Data Frames</a>
    </li>
    <li>
      <a href="hw9-data-wrangling.html">HW 9 - Data Wrangling</a>
    </li>
    <li>
      <a href="hw10-data-visualization.html">HW 10 - Data Visualization</a>
    </li>
    <li>
      <a href="hw11-python-data-structures.html">HW 11 - Python Data Structures</a>
    </li>
    <li>
      <a href="hw12-reproducible-reporting.html">HW 12 - Reproducible Reporting</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="far fa-bookmark"></span>
     
    References
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="ref-getting-help.html">
        <span class="fa fa-question-circle"></span>
         
        Getting Help
      </a>
    </li>
    <li>
      <a href="ref-programming.html">
        <span class="fa fa-terminal"></span>
         
        Programming in R
      </a>
    </li>
    <li>
      <a href="ref-visualizing-data.html">
        <span class="fa fa-chart-bar"></span>
         
        Visualizing Data
      </a>
    </li>
    <li>
      <a href="ref-rmarkdown.html">
        <span class="fa fa-feather-alt"></span>
         
        R Markdown
      </a>
    </li>
    <li>
      <a href="ref-other.html">
        <span class="fa fa-expand"></span>
         
        Other
      </a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fas fa-tools"></span>
     
    Tools
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="autograder.html">
        <span class="fas fa-tasks"></span>
         
        Autograder
      </a>
    </li>
    <li>
      <a href="https://emse-p4a-f20.slack.com">
        <span class="fab fa-slack"></span>
         
        Slack
      </a>
    </li>
    <li>
      <a href="https://rstudio.seas.gwu.edu/">
        <span class="fab fa-r-project"></span>
         
        RStudio Server
      </a>
    </li>
    <li>
      <a href="https://jhelvy.appointlet.com/s/20-minute-meeting">
        <span class="fas fa-user-clock"></span>
         
        Schedule a meeting
      </a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-bars"></span>
     
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="about.html">
        <span class="fa fa-info-circle"></span>
         
        About
      </a>
    </li>
    <li>
      <a href="LICENSE.html">
        <span class="fa fa-gavel"></span>
         
        License
      </a>
    </li>
    <li>
      <a href="mailto:jph@gwu.edu">
        <span class="fa fa-envelope"></span>
         
        Contact
      </a>
    </li>
    <li>
      <a href="https://github.com/emse-p4a-gwu/2020-Fall/">
        <span class="fa fa-github"></span>
         
        Source files
      </a>
    </li>
  </ul>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Data Analysis 2 - Data Wrangling</h1>

</div>


<blockquote>
<h3 id="learning-objectives">Learning Objectives</h3>
<ul>
<li>Describe the purpose of the <code>dplyr</code> package.</li>
<li>Select certain <em>columns</em> in a data frame with the <code>select</code> function.</li>
<li>Select certain <em>rows</em> in a data frame according to filtering conditions with the <code>filter</code> function.</li>
<li>Link the output of one <code>dplyr</code> function to the input of another function with the “pipe” operator <code>%&gt;%</code>.</li>
<li>Add new columns to a data frame that are functions of existing columns with the <code>mutate</code> function.</li>
<li>Sort data frames using the <code>arrange()</code> function.</li>
<li>Use the split-apply-combine concept for data analysis.</li>
<li>Use <code>summarize</code>, <code>group_by</code>, and <code>count</code> to split a data frame into groups of observations, apply summary statistics for each group, and then combine the results.</li>
<li>Export a data frame to a .csv file.</li>
</ul>
<h3 id="suggested-readings">Suggested Readings</h3>
<ul>
<li><a href="https://r4ds.had.co.nz/transform.html">Chapter 5</a> of “R for Data Science”, by Garrett Grolemund and Hadley Wickham</li>
<li><a href="https://resources.rstudio.com/the-essentials-of-data-science/data-transformation"><code>dplyr</code> cheatsheet</a></li>
</ul>
</blockquote>
<hr />
<div id="r-setup" class="section level1">
<h1><span class="header-section-number">1</span> R Setup</h1>
<p>Before we get started, let’s set up our analysis environment:</p>
<ol style="list-style-type: decimal">
<li>Open up your “data-analysis-tutorial” R Project that you created in the last lesson - if you didn’t do this, <a href="L10-data-analysis-1-data-frames.html#41_r_setup">go back and do it now</a>.</li>
<li>Create a new <code>.R</code> file (File &gt; New File &gt; R Script), and save it as “<code>data_wrangling.R</code>” inside your “data-analysis-tutorial” R Project folder.</li>
<li>Use the <code>download.file()</code> function to download the <code>wildlife_impacts.csv</code> dataset, and save it in the <code>data</code> folder in your R Project:</li>
</ol>
<pre class="r"><code>download.file(
    url = &quot;https://github.com/emse6574-gwu/2019-Fall/raw/gh-pages/data/wildlife_impacts.csv&quot;,
    destfile = file.path(&#39;data&#39;, &#39;wildlife_impacts.csv&#39;)
)</code></pre>
<p>For this lesson, we are going to use the <a href="https://wildlife.faa.gov/">FAA Wildlife Strike Database</a>, which contains records of reported wildlife strikes with aircraft since 1990. Since aircraft-wildlife impacts are voluntarily reported, the database only contains information from airlines, airports, pilots, and other sources and does not represent all strikes. Each row in the dataset holds information for a single strike event with the following columns:</p>
<table>
<colgroup>
<col width="24%" />
<col width="15%" />
<col width="60%" />
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Class</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>incident_date</td>
<td>date</td>
<td>Date of incident</td>
</tr>
<tr class="even">
<td>state</td>
<td>character</td>
<td>State</td>
</tr>
<tr class="odd">
<td>airport_id</td>
<td>character</td>
<td>ICAO Airport ID</td>
</tr>
<tr class="even">
<td>airport</td>
<td>character</td>
<td>Airport Name</td>
</tr>
<tr class="odd">
<td>operator</td>
<td>character</td>
<td>Operator/Airline</td>
</tr>
<tr class="even">
<td>atype</td>
<td>character</td>
<td>Airline type</td>
</tr>
<tr class="odd">
<td>type_eng</td>
<td>character</td>
<td>Engine type</td>
</tr>
<tr class="even">
<td>species_id</td>
<td>character</td>
<td>Species ID</td>
</tr>
<tr class="odd">
<td>species</td>
<td>character</td>
<td>Species</td>
</tr>
<tr class="even">
<td>damage</td>
<td>character</td>
<td>Damage: N None M Minor, M Uncertain, S Substantial, D Destroyed</td>
</tr>
<tr class="odd">
<td>num_engs</td>
<td>character</td>
<td>Number of engines</td>
</tr>
<tr class="even">
<td>incident_month</td>
<td>double</td>
<td>Incident month</td>
</tr>
<tr class="odd">
<td>incident_year</td>
<td>double</td>
<td>Incident year</td>
</tr>
<tr class="even">
<td>time_of_day</td>
<td>character</td>
<td>Incident Time of day</td>
</tr>
<tr class="odd">
<td>time</td>
<td>double</td>
<td>Incident time</td>
</tr>
<tr class="even">
<td>height</td>
<td>double</td>
<td>Plane height at impact (feet)</td>
</tr>
<tr class="odd">
<td>speed</td>
<td>double</td>
<td>Plane speed at impact (knots)</td>
</tr>
<tr class="even">
<td>phase_of_flt</td>
<td>character</td>
<td>Phase of flight at impact</td>
</tr>
<tr class="odd">
<td>sky</td>
<td>character</td>
<td>Sky condition</td>
</tr>
<tr class="even">
<td>precip</td>
<td>character</td>
<td>Precipitation</td>
</tr>
<tr class="odd">
<td>cost_repairs_infl_adj</td>
<td>double</td>
<td>Cost of repairs adjusted for inflation</td>
</tr>
</tbody>
</table>
<p>Let’s load our libraries and read in the data:</p>
<pre class="r"><code>library(readr)
library(dplyr)
df &lt;- read_csv(file.path(&#39;data&#39;, &#39;wildlife_impacts.csv&#39;))</code></pre>
<p>Just like in the last lesson, a good starting point when working with a new dataset is to view some quick summaries. Here’s another summary function (<code>glimpse()</code>) that is similar to <code>str()</code>:</p>
<pre class="r"><code>glimpse(df)</code></pre>
<pre><code>## Rows: 56,978
## Columns: 21
## $ incident_date         [3m[90m&lt;dttm&gt;[39m[23m 2018-12-31, 2018-12-29, 2018-12-29, 2018-12-27…
## $ state                 [3m[90m&lt;chr&gt;[39m[23m &quot;FL&quot;, &quot;IN&quot;, &quot;N/A&quot;, &quot;N/A&quot;, &quot;N/A&quot;, &quot;FL&quot;, &quot;FL&quot;, &quot;N…
## $ airport_id            [3m[90m&lt;chr&gt;[39m[23m &quot;KMIA&quot;, &quot;KIND&quot;, &quot;ZZZZ&quot;, &quot;ZZZZ&quot;, &quot;ZZZZ&quot;, &quot;KMIA&quot;,…
## $ airport               [3m[90m&lt;chr&gt;[39m[23m &quot;MIAMI INTL&quot;, &quot;INDIANAPOLIS INTL ARPT&quot;, &quot;UNKNOW…
## $ operator              [3m[90m&lt;chr&gt;[39m[23m &quot;AMERICAN AIRLINES&quot;, &quot;AMERICAN AIRLINES&quot;, &quot;AMER…
## $ atype                 [3m[90m&lt;chr&gt;[39m[23m &quot;B-737-800&quot;, &quot;B-737-800&quot;, &quot;UNKNOWN&quot;, &quot;B-737-900…
## $ type_eng              [3m[90m&lt;chr&gt;[39m[23m &quot;D&quot;, &quot;D&quot;, NA, &quot;D&quot;, &quot;D&quot;, &quot;D&quot;, &quot;D&quot;, &quot;D&quot;, &quot;D&quot;, &quot;D&quot;…
## $ species_id            [3m[90m&lt;chr&gt;[39m[23m &quot;UNKBL&quot;, &quot;R&quot;, &quot;R2004&quot;, &quot;N5205&quot;, &quot;J2139&quot;, &quot;UNKB&quot;…
## $ species               [3m[90m&lt;chr&gt;[39m[23m &quot;Unknown bird - large&quot;, &quot;Owls&quot;, &quot;Short-eared ow…
## $ damage                [3m[90m&lt;chr&gt;[39m[23m &quot;M?&quot;, &quot;N&quot;, NA, &quot;M?&quot;, &quot;M?&quot;, &quot;N&quot;, &quot;N&quot;, &quot;N&quot;, &quot;N&quot;, …
## $ num_engs              [3m[90m&lt;dbl&gt;[39m[23m 2, 2, NA, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2…
## $ incident_month        [3m[90m&lt;dbl&gt;[39m[23m 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,…
## $ incident_year         [3m[90m&lt;dbl&gt;[39m[23m 2018, 2018, 2018, 2018, 2018, 2018, 2018, 2018,…
## $ time_of_day           [3m[90m&lt;chr&gt;[39m[23m &quot;Day&quot;, &quot;Night&quot;, NA, NA, NA, &quot;Day&quot;, &quot;Night&quot;, NA,…
## $ time                  [3m[90m&lt;dbl&gt;[39m[23m 1207, 2355, NA, NA, NA, 955, 948, NA, NA, 1321,…
## $ height                [3m[90m&lt;dbl&gt;[39m[23m 700, 0, NA, NA, NA, NA, 600, NA, NA, 0, NA, 0, …
## $ speed                 [3m[90m&lt;dbl&gt;[39m[23m 200, NA, NA, NA, NA, NA, 145, NA, NA, 130, NA, …
## $ phase_of_flt          [3m[90m&lt;chr&gt;[39m[23m &quot;Climb&quot;, &quot;Landing Roll&quot;, NA, NA, NA, &quot;Approach&quot;…
## $ sky                   [3m[90m&lt;chr&gt;[39m[23m &quot;Some Cloud&quot;, NA, NA, NA, NA, NA, &quot;Some Cloud&quot;,…
## $ precip                [3m[90m&lt;chr&gt;[39m[23m &quot;None&quot;, NA, NA, NA, NA, NA, &quot;None&quot;, NA, NA, &quot;No…
## $ cost_repairs_infl_adj [3m[90m&lt;dbl&gt;[39m[23m NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…</code></pre>
<p>Wow, there have been 56,978 reported wildlife strikes over the 29 period from 1990 to 2019! On a daily average that comes out to:</p>
<pre class="r"><code>nrow(df) / (2019 - 1990) / 365</code></pre>
<pre><code>## [1] 5.3829</code></pre>
<p>…over 5 strikes per day!</p>
</div>
<div id="data-wrangling-with-dplyr" class="section level1">
<h1><span class="header-section-number">2</span> Data wrangling with <code>dplyr</code></h1>
<p><img src="images/horst_monsters_data_wrangling.png" width="500" /> <a href="https://github.com/allisonhorst">[Art by Allison Horst]</a></p>
<p>“Data Wrangling” refers to the art of getting your data into R in a useful form for visualization and modeling. Wrangling is the first step in the general data science process:</p>
<center>
<img src="images/data-wrangle.png" />
</center>
<div id="what-is-dplyr" class="section level2">
<h2><span class="header-section-number">2.1</span> What is <code>dplyr</code></h2>
<p>As we saw in the last section, we can use brackets (<code>[]</code>) to access elements of a data frame. While this is handy, it can be cumbersome and difficult to read, especially for complicated operations.</p>
<p><strong>Enter <code>dplyr</code></strong></p>
<p>The <code>dplyr</code> package was designed to make tabular data wrangling easier to perform and read. It pairs nicely with other libraries, such as <strong><code>ggplot2</code></strong> for visualizing data (which we’ll cover next week). Together, <code>dplyr</code>, <code>ggplot2</code>, and a handful of other packages make up what is known as the <a href="https://www.tidyverse.org/">“Tidyverse”</a> - an opinionated collection of R packages designed for data science. You can load all of the tidyverse packages at once using the <code>library(tidyverse)</code> command, but for now we’re just going to install and use each package one at a time - starting with <code>dplyr</code>:</p>
<pre class="r"><code>install.packages(&quot;dplyr&quot;)</code></pre>
<p>In this lesson, we are going to learn some of the most common <code>dplyr</code> functions:</p>
<ul>
<li><code>select()</code>: subset columns</li>
<li><code>filter()</code>: subset rows on conditions</li>
<li><code>mutate()</code>: create new columns by using information from other columns</li>
<li><code>arrange()</code>: sort results</li>
<li><code>group_by()</code>: group data to perform grouped operations</li>
<li><code>summarize()</code>: create summary statistics (usually on grouped data)</li>
<li><code>count()</code>: count discrete rows</li>
</ul>
</div>
<div id="select-columns-with-select" class="section level2">
<h2><span class="header-section-number">2.2</span> Select columns with <code>select()</code></h2>
<p><img src="images/rstudio-cheatsheet-select.png" width="500" /></p>
<p>To select specific columns, use <code>select()</code>. The first argument to this function is the data frame (<code>df</code>), and the subsequent arguments are the columns to keep:</p>
<pre class="r"><code># Select only a few columns
select(df, state, damage, time_of_day)</code></pre>
<pre><code>## [90m# A tibble: 56,978 x 3[39m
##    state damage time_of_day
##    [3m[90m&lt;chr&gt;[39m[23m [3m[90m&lt;chr&gt;[39m[23m  [3m[90m&lt;chr&gt;[39m[23m      
## [90m 1[39m FL    M?     Day        
## [90m 2[39m IN    N      Night      
## [90m 3[39m N/A   [31mNA[39m     [31mNA[39m         
## [90m 4[39m N/A   M?     [31mNA[39m         
## [90m 5[39m N/A   M?     [31mNA[39m         
## [90m 6[39m FL    N      Day        
## [90m 7[39m FL    N      Night      
## [90m 8[39m N/A   N      [31mNA[39m         
## [90m 9[39m N/A   N      [31mNA[39m         
## [90m10[39m FL    N      Day        
## [90m# … with 56,968 more rows[39m</code></pre>
<p>To select all columns <em>except</em> certain ones, put a <code>-</code> sign in front of the variable to exclude it:</p>
<pre class="r"><code>select(df, -state, -damage, -time_of_day)</code></pre>
<pre><code>## [90m# A tibble: 56,978 x 18[39m
##    incident_date       airport_id airport operator atype type_eng species_id
##    [3m[90m&lt;dttm&gt;[39m[23m              [3m[90m&lt;chr&gt;[39m[23m      [3m[90m&lt;chr&gt;[39m[23m   [3m[90m&lt;chr&gt;[39m[23m    [3m[90m&lt;chr&gt;[39m[23m [3m[90m&lt;chr&gt;[39m[23m    [3m[90m&lt;chr&gt;[39m[23m     
## [90m 1[39m 2018-12-31 [90m00:00:00[39m KMIA       MIAMI … AMERICA… B-73… D        UNKBL     
## [90m 2[39m 2018-12-29 [90m00:00:00[39m KIND       INDIAN… AMERICA… B-73… D        R         
## [90m 3[39m 2018-12-29 [90m00:00:00[39m ZZZZ       UNKNOWN AMERICA… UNKN… [31mNA[39m       R2004     
## [90m 4[39m 2018-12-27 [90m00:00:00[39m ZZZZ       UNKNOWN AMERICA… B-73… D        N5205     
## [90m 5[39m 2018-12-27 [90m00:00:00[39m ZZZZ       UNKNOWN AMERICA… B-73… D        J2139     
## [90m 6[39m 2018-12-27 [90m00:00:00[39m KMIA       MIAMI … AMERICA… A-319 D        UNKB      
## [90m 7[39m 2018-12-27 [90m00:00:00[39m KMCO       ORLAND… AMERICA… A-321 D        UNKBS     
## [90m 8[39m 2018-12-26 [90m00:00:00[39m ZZZZ       UNKNOWN AMERICA… B-73… D        ZT001     
## [90m 9[39m 2018-12-23 [90m00:00:00[39m ZZZZ       UNKNOWN AMERICA… A-321 D        ZT101     
## [90m10[39m 2018-12-23 [90m00:00:00[39m KFLL       FORT L… AMERICA… B-73… D        I1301     
## [90m# … with 56,968 more rows, and 11 more variables: species [3m[90m&lt;chr&gt;[90m[23m,[39m
## [90m#   num_engs [3m[90m&lt;dbl&gt;[90m[23m, incident_month [3m[90m&lt;dbl&gt;[90m[23m, incident_year [3m[90m&lt;dbl&gt;[90m[23m, time [3m[90m&lt;dbl&gt;[90m[23m,[39m
## [90m#   height [3m[90m&lt;dbl&gt;[90m[23m, speed [3m[90m&lt;dbl&gt;[90m[23m, phase_of_flt [3m[90m&lt;chr&gt;[90m[23m, sky [3m[90m&lt;chr&gt;[90m[23m, precip [3m[90m&lt;chr&gt;[90m[23m,[39m
## [90m#   cost_repairs_infl_adj [3m[90m&lt;dbl&gt;[90m[23m[39m</code></pre>
<p>Some additional options to select columns based on a specific criteria include:</p>
<ol style="list-style-type: decimal">
<li><code>ends_with()</code> = Select columns that end with a character string</li>
<li><code>contains()</code> = Select columns that contain a character string</li>
<li><code>matches()</code> = Select columns that match a regular expression</li>
<li><code>one_of()</code> = Select column names that are from a group of names</li>
</ol>
</div>
<div id="select-rows-with-filter" class="section level2">
<h2><span class="header-section-number">2.3</span> Select rows with <code>filter()</code></h2>
<p><img src="images/rstudio-cheatsheet-filter.png" width="500" /></p>
<p>Filter the rows for wildlife impacts that occurred in DC:</p>
<pre class="r"><code>filter(df, state == &#39;DC&#39;)</code></pre>
<pre><code>## [90m# A tibble: 1,228 x 21[39m
##    incident_date       state airport_id airport operator atype type_eng
##    [3m[90m&lt;dttm&gt;[39m[23m              [3m[90m&lt;chr&gt;[39m[23m [3m[90m&lt;chr&gt;[39m[23m      [3m[90m&lt;chr&gt;[39m[23m   [3m[90m&lt;chr&gt;[39m[23m    [3m[90m&lt;chr&gt;[39m[23m [3m[90m&lt;chr&gt;[39m[23m   
## [90m 1[39m 2018-10-23 [90m00:00:00[39m DC    KDCA       RONALD… AMERICA… B-73… D       
## [90m 2[39m 2018-10-17 [90m00:00:00[39m DC    KDCA       RONALD… AMERICA… B-73… D       
## [90m 3[39m 2018-10-16 [90m00:00:00[39m DC    KDCA       RONALD… AMERICA… B-73… D       
## [90m 4[39m 2018-10-12 [90m00:00:00[39m DC    KDCA       RONALD… AMERICA… B-73… D       
## [90m 5[39m 2018-09-04 [90m00:00:00[39m DC    KDCA       RONALD… AMERICA… A-319 D       
## [90m 6[39m 2018-09-01 [90m00:00:00[39m DC    KDCA       RONALD… AMERICA… A-321 D       
## [90m 7[39m 2018-08-31 [90m00:00:00[39m DC    KIAD       WASHIN… AMERICA… A-319 D       
## [90m 8[39m 2018-08-23 [90m00:00:00[39m DC    KDCA       RONALD… AMERICA… EMB-… D       
## [90m 9[39m 2018-08-13 [90m00:00:00[39m DC    KIAD       WASHIN… AMERICA… MD-82 D       
## [90m10[39m 2018-08-01 [90m00:00:00[39m DC    KIAD       WASHIN… AMERICA… CRJ7… D       
## [90m# … with 1,218 more rows, and 14 more variables: species_id [3m[90m&lt;chr&gt;[90m[23m,[39m
## [90m#   species [3m[90m&lt;chr&gt;[90m[23m, damage [3m[90m&lt;chr&gt;[90m[23m, num_engs [3m[90m&lt;dbl&gt;[90m[23m, incident_month [3m[90m&lt;dbl&gt;[90m[23m,[39m
## [90m#   incident_year [3m[90m&lt;dbl&gt;[90m[23m, time_of_day [3m[90m&lt;chr&gt;[90m[23m, time [3m[90m&lt;dbl&gt;[90m[23m, height [3m[90m&lt;dbl&gt;[90m[23m,[39m
## [90m#   speed [3m[90m&lt;dbl&gt;[90m[23m, phase_of_flt [3m[90m&lt;chr&gt;[90m[23m, sky [3m[90m&lt;chr&gt;[90m[23m, precip [3m[90m&lt;chr&gt;[90m[23m,[39m
## [90m#   cost_repairs_infl_adj [3m[90m&lt;dbl&gt;[90m[23m[39m</code></pre>
<p>Filter the rows for wildlife impacts that cost more than $1 million in damages:</p>
<pre class="r"><code>filter(df, cost_repairs_infl_adj &gt; 10^6)</code></pre>
<pre><code>## [90m# A tibble: 41 x 21[39m
##    incident_date       state airport_id airport operator atype type_eng
##    [3m[90m&lt;dttm&gt;[39m[23m              [3m[90m&lt;chr&gt;[39m[23m [3m[90m&lt;chr&gt;[39m[23m      [3m[90m&lt;chr&gt;[39m[23m   [3m[90m&lt;chr&gt;[39m[23m    [3m[90m&lt;chr&gt;[39m[23m [3m[90m&lt;chr&gt;[39m[23m   
## [90m 1[39m 2015-05-26 [90m00:00:00[39m N/A   SVMI       SIMON … AMERICA… B-73… D       
## [90m 2[39m 2015-04-25 [90m00:00:00[39m FL    KJAX       JACKSO… AMERICA… A-319 D       
## [90m 3[39m 2015-04-02 [90m00:00:00[39m MA    KBOS       GENERA… AMERICA… B-73… D       
## [90m 4[39m 2001-04-02 [90m00:00:00[39m N/A   LFPG       CHARLE… AMERICA… B-76… D       
## [90m 5[39m 2015-10-08 [90m00:00:00[39m WA    KSEA       SEATTL… DELTA A… A-330 D       
## [90m 6[39m 2015-09-23 [90m00:00:00[39m UT    KSLC       SALT L… DELTA A… B-73… D       
## [90m 7[39m 2008-10-25 [90m00:00:00[39m UT    KSLC       SALT L… DELTA A… DC-9… D       
## [90m 8[39m 2007-12-02 [90m00:00:00[39m N/A   GOOY       DAKAY-… DELTA A… B-76… D       
## [90m 9[39m 2007-11-22 [90m00:00:00[39m N/A   LFMN       NICE C… DELTA A… B-76… D       
## [90m10[39m 2011-07-30 [90m00:00:00[39m CA    KBUR       BOB HO… SOUTHWE… B-73… D       
## [90m# … with 31 more rows, and 14 more variables: species_id [3m[90m&lt;chr&gt;[90m[23m, species [3m[90m&lt;chr&gt;[90m[23m,[39m
## [90m#   damage [3m[90m&lt;chr&gt;[90m[23m, num_engs [3m[90m&lt;dbl&gt;[90m[23m, incident_month [3m[90m&lt;dbl&gt;[90m[23m, incident_year [3m[90m&lt;dbl&gt;[90m[23m,[39m
## [90m#   time_of_day [3m[90m&lt;chr&gt;[90m[23m, time [3m[90m&lt;dbl&gt;[90m[23m, height [3m[90m&lt;dbl&gt;[90m[23m, speed [3m[90m&lt;dbl&gt;[90m[23m,[39m
## [90m#   phase_of_flt [3m[90m&lt;chr&gt;[90m[23m, sky [3m[90m&lt;chr&gt;[90m[23m, precip [3m[90m&lt;chr&gt;[90m[23m, cost_repairs_infl_adj [3m[90m&lt;dbl&gt;[90m[23m[39m</code></pre>
</div>
<div id="sequence-operations-with-pipes" class="section level2">
<h2><span class="header-section-number">2.4</span> Sequence operations with pipes (<code>%&gt;%</code>)</h2>
<p><img src="images/magrittr.png" width="200" /> (logo is a reference to <a href="https://en.wikipedia.org/wiki/The_Treachery_of_Images">The Treachery of Images</a>)</p>
<p>What if you want to select and filter at the same time? Well, one way to do this is to use intermediate steps. To do this, you first create a temporary data frame and then use that as input to the next function, like this:</p>
<pre class="r"><code>dc_impacts &lt;- filter(df, state == &#39;DC&#39;)
dc_impacts_airlineTime &lt;- select(dc_impacts, operator, time, time_of_day)
head(dc_impacts_airlineTime)</code></pre>
<pre><code>## [90m# A tibble: 6 x 3[39m
##   operator           time time_of_day
##   [3m[90m&lt;chr&gt;[39m[23m             [3m[90m&lt;dbl&gt;[39m[23m [3m[90m&lt;chr&gt;[39m[23m      
## [90m1[39m AMERICAN AIRLINES  [4m2[24m130 Night      
## [90m2[39m AMERICAN AIRLINES  [4m2[24m043 Night      
## [90m3[39m AMERICAN AIRLINES   730 Dawn       
## [90m4[39m AMERICAN AIRLINES  [4m2[24m245 Night      
## [90m5[39m AMERICAN AIRLINES  [4m2[24m150 Night      
## [90m6[39m AMERICAN AIRLINES  [4m2[24m022 Night</code></pre>
<p>This works, but it can also clutter up your workspace with lots of objects with different names.</p>
<p>Another approach is to use <strong>pipes</strong>, which is a more recent addition to R. Pipes let you take the output of one function and send it directly to the next, which is useful when you need to do many things to the same dataset.</p>
<p>The pipe operator is <code>%&gt;%</code> and comes from the <a href="https://github.com/tidyverse/magrittr"><code>magrittr</code></a> package, which is installed automatically with <code>dplyr</code>. If you use RStudio, you can type the pipe with <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>M</kbd> if you have a PC or <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>M</kbd> if you have a Mac. Here’s the same thing as the previous example but with pipes:</p>
<pre class="r"><code>df %&gt;%
    filter(state == &#39;DC&#39;) %&gt;%
    select(operator, time, time_of_day) %&gt;%
    head()</code></pre>
<pre><code>## [90m# A tibble: 6 x 3[39m
##   operator           time time_of_day
##   [3m[90m&lt;chr&gt;[39m[23m             [3m[90m&lt;dbl&gt;[39m[23m [3m[90m&lt;chr&gt;[39m[23m      
## [90m1[39m AMERICAN AIRLINES  [4m2[24m130 Night      
## [90m2[39m AMERICAN AIRLINES  [4m2[24m043 Night      
## [90m3[39m AMERICAN AIRLINES   730 Dawn       
## [90m4[39m AMERICAN AIRLINES  [4m2[24m245 Night      
## [90m5[39m AMERICAN AIRLINES  [4m2[24m150 Night      
## [90m6[39m AMERICAN AIRLINES  [4m2[24m022 Night</code></pre>
<p>In the above code, we use the pipe to send the <code>df</code> data frame first through <code>filter()</code> to keep only rows from DC, and then through <code>select()</code> to keep only the columns <code>operator</code>, <code>time</code>, and <code>time_of_day</code>.</p>
<p>Since <code>%&gt;%</code> takes the object on its left and passes it as the first argument to the function on its right, we don’t need to explicitly include the data frame as an argument to the <code>filter()</code> and <code>select()</code> functions.</p>
<p>Consider reading the <code>%&gt;%</code> operator as the words “…and then…”. For instance, in the above example I would read the code as “First, filter to only data from DC, <strong>and then</strong> select the columns <code>operator</code>, <code>time</code>, and <code>time_of_day</code>, <strong>and then</strong> show the first 6 rows.”</p>
<p>Here’s another analogy:</p>
<p><strong>Without Pipes</strong>:</p>
<pre class="r"><code>leave_house(get_dressed(get_out_of_bed(wake_up(me))))</code></pre>
<p><strong>With Pipes</strong>:</p>
<pre class="r"><code>me %&gt;%
    wake_up %&gt;%
    get_out_of_bed %&gt;%
    get_dressed %&gt;%
    leave_house</code></pre>
<p>In the above example, adding pipes makes the flow of operations easier to read from left to right, with the <code>%&gt;%</code> operator reading as “…and then…”</p>
<p>If you want to create a new object with the output of a “pipeline”, you just put the object name at the start of the first pipe:</p>
<pre class="r"><code>dc_impacts &lt;- df %&gt;%
    filter(state == &#39;DC&#39;) %&gt;%
    select(operator, time, time_of_day)
head(dc_impacts)</code></pre>
<pre><code>## [90m# A tibble: 6 x 3[39m
##   operator           time time_of_day
##   [3m[90m&lt;chr&gt;[39m[23m             [3m[90m&lt;dbl&gt;[39m[23m [3m[90m&lt;chr&gt;[39m[23m      
## [90m1[39m AMERICAN AIRLINES  [4m2[24m130 Night      
## [90m2[39m AMERICAN AIRLINES  [4m2[24m043 Night      
## [90m3[39m AMERICAN AIRLINES   730 Dawn       
## [90m4[39m AMERICAN AIRLINES  [4m2[24m245 Night      
## [90m5[39m AMERICAN AIRLINES  [4m2[24m150 Night      
## [90m6[39m AMERICAN AIRLINES  [4m2[24m022 Night</code></pre>
</div>
<div id="sort-rows-with-arrange" class="section level2">
<h2><span class="header-section-number">2.5</span> Sort rows with <code>arrange()</code></h2>
<p>Use the <code>arrange()</code> function to sort a data frame by a column. For example, if you wanted to view the least expensive accidents, you could arrange the data frame by the variable <code>cost_repairs_infl_adj</code>:</p>
<pre class="r"><code># Arrange by least expensive accident
df %&gt;%
    arrange(cost_repairs_infl_adj)</code></pre>
<pre><code>## [90m# A tibble: 56,978 x 21[39m
##    incident_date       state airport_id airport operator atype type_eng
##    [3m[90m&lt;dttm&gt;[39m[23m              [3m[90m&lt;chr&gt;[39m[23m [3m[90m&lt;chr&gt;[39m[23m      [3m[90m&lt;chr&gt;[39m[23m   [3m[90m&lt;chr&gt;[39m[23m    [3m[90m&lt;chr&gt;[39m[23m [3m[90m&lt;chr&gt;[39m[23m   
## [90m 1[39m 2013-09-05 [90m00:00:00[39m MI    KFNT       BISHOP… SOUTHWE… B-73… D       
## [90m 2[39m 2011-04-17 [90m00:00:00[39m TX    KDFW       DALLAS… AMERICA… MD-80 D       
## [90m 3[39m 2018-07-10 [90m00:00:00[39m NM    KABQ       ALBUQU… SOUTHWE… B-73… D       
## [90m 4[39m 2017-10-31 [90m00:00:00[39m PA    KPIT       PITTSB… AMERICA… B-73… D       
## [90m 5[39m 2014-01-17 [90m00:00:00[39m UT    KSLC       SALT L… SOUTHWE… B-73… D       
## [90m 6[39m 2006-04-28 [90m00:00:00[39m TX    KIAH       GEORGE… UNITED … B-73… D       
## [90m 7[39m 2005-04-13 [90m00:00:00[39m N/A   ZZZZ       UNKNOWN UNITED … B-76… D       
## [90m 8[39m 2004-06-17 [90m00:00:00[39m N/A   ZZZZ       UNKNOWN UNITED … B-73… D       
## [90m 9[39m 2004-04-22 [90m00:00:00[39m N/A   ZZZZ       UNKNOWN UNITED … B-76… D       
## [90m10[39m 2018-10-20 [90m00:00:00[39m TX    KDAL       DALLAS… SOUTHWE… B-73… D       
## [90m# … with 56,968 more rows, and 14 more variables: species_id [3m[90m&lt;chr&gt;[90m[23m,[39m
## [90m#   species [3m[90m&lt;chr&gt;[90m[23m, damage [3m[90m&lt;chr&gt;[90m[23m, num_engs [3m[90m&lt;dbl&gt;[90m[23m, incident_month [3m[90m&lt;dbl&gt;[90m[23m,[39m
## [90m#   incident_year [3m[90m&lt;dbl&gt;[90m[23m, time_of_day [3m[90m&lt;chr&gt;[90m[23m, time [3m[90m&lt;dbl&gt;[90m[23m, height [3m[90m&lt;dbl&gt;[90m[23m,[39m
## [90m#   speed [3m[90m&lt;dbl&gt;[90m[23m, phase_of_flt [3m[90m&lt;chr&gt;[90m[23m, sky [3m[90m&lt;chr&gt;[90m[23m, precip [3m[90m&lt;chr&gt;[90m[23m,[39m
## [90m#   cost_repairs_infl_adj [3m[90m&lt;dbl&gt;[90m[23m[39m</code></pre>
<p>To sort in descending order, add the <code>desc()</code> function inside the <code>arrange()</code> function. For example, here are the <em>most</em> expensive accidents:</p>
<pre class="r"><code># Arrange by most expensive accident
df %&gt;%
    arrange(desc(cost_repairs_infl_adj))</code></pre>
<pre><code>## [90m# A tibble: 56,978 x 21[39m
##    incident_date       state airport_id airport operator atype type_eng
##    [3m[90m&lt;dttm&gt;[39m[23m              [3m[90m&lt;chr&gt;[39m[23m [3m[90m&lt;chr&gt;[39m[23m      [3m[90m&lt;chr&gt;[39m[23m   [3m[90m&lt;chr&gt;[39m[23m    [3m[90m&lt;chr&gt;[39m[23m [3m[90m&lt;chr&gt;[39m[23m   
## [90m 1[39m 2009-02-03 [90m00:00:00[39m CO    KDEN       DENVER… UNITED … B-75… D       
## [90m 2[39m 2007-11-22 [90m00:00:00[39m N/A   LFMN       NICE C… DELTA A… B-76… D       
## [90m 3[39m 2011-09-26 [90m00:00:00[39m CO    KDEN       DENVER… UNITED … B-75… D       
## [90m 4[39m 2017-07-11 [90m00:00:00[39m CO    KDEN       DENVER… UNITED … B-73… D       
## [90m 5[39m 2008-10-25 [90m00:00:00[39m UT    KSLC       SALT L… DELTA A… DC-9… D       
## [90m 6[39m 2011-07-30 [90m00:00:00[39m CA    KBUR       BOB HO… SOUTHWE… B-73… D       
## [90m 7[39m 2001-12-06 [90m00:00:00[39m MI    KDTW       DETROI… SOUTHWE… B-73… D       
## [90m 8[39m 2003-04-15 [90m00:00:00[39m CA    KSFO       SAN FR… UNITED … B-73… D       
## [90m 9[39m 2005-09-06 [90m00:00:00[39m CO    KDEN       DENVER… UNITED … B-73… D       
## [90m10[39m 2005-04-20 [90m00:00:00[39m N/A   ZZZZ       UNKNOWN UNITED … B-77… D       
## [90m# … with 56,968 more rows, and 14 more variables: species_id [3m[90m&lt;chr&gt;[90m[23m,[39m
## [90m#   species [3m[90m&lt;chr&gt;[90m[23m, damage [3m[90m&lt;chr&gt;[90m[23m, num_engs [3m[90m&lt;dbl&gt;[90m[23m, incident_month [3m[90m&lt;dbl&gt;[90m[23m,[39m
## [90m#   incident_year [3m[90m&lt;dbl&gt;[90m[23m, time_of_day [3m[90m&lt;chr&gt;[90m[23m, time [3m[90m&lt;dbl&gt;[90m[23m, height [3m[90m&lt;dbl&gt;[90m[23m,[39m
## [90m#   speed [3m[90m&lt;dbl&gt;[90m[23m, phase_of_flt [3m[90m&lt;chr&gt;[90m[23m, sky [3m[90m&lt;chr&gt;[90m[23m, precip [3m[90m&lt;chr&gt;[90m[23m,[39m
## [90m#   cost_repairs_infl_adj [3m[90m&lt;dbl&gt;[90m[23m[39m</code></pre>
</div>
<div id="create-new-variables-with-mutate" class="section level2">
<h2><span class="header-section-number">2.6</span> Create new variables with <code>mutate()</code></h2>
<p><img src="images/rstudio-cheatsheet-mutate.png" width="500" /></p>
<p>You will often need to create new columns based on the values in existing columns. For this use <code>mutate()</code>. For example, let’s create a new variable converting the <code>height</code> variable from feet to miles:</p>
<pre class="r"><code>df %&gt;%
    mutate(height_miles = height / 5280) %&gt;%
    select(height, height_miles)</code></pre>
<pre><code>## [90m# A tibble: 56,978 x 2[39m
##    height height_miles
##     [3m[90m&lt;dbl&gt;[39m[23m        [3m[90m&lt;dbl&gt;[39m[23m
## [90m 1[39m    700        0.133
## [90m 2[39m      0        0    
## [90m 3[39m     [31mNA[39m       [31mNA[39m    
## [90m 4[39m     [31mNA[39m       [31mNA[39m    
## [90m 5[39m     [31mNA[39m       [31mNA[39m    
## [90m 6[39m     [31mNA[39m       [31mNA[39m    
## [90m 7[39m    600        0.114
## [90m 8[39m     [31mNA[39m       [31mNA[39m    
## [90m 9[39m     [31mNA[39m       [31mNA[39m    
## [90m10[39m      0        0    
## [90m# … with 56,968 more rows[39m</code></pre>
<p>You can also create a second new column based on the first new column within the same call of <code>mutate()</code>:</p>
<pre class="r"><code>df %&gt;%
    mutate(height_miles = height / 5280,
           height_half_miles = height_miles / 2) %&gt;%
    select(height, height_miles, height_half_miles)</code></pre>
<pre><code>## [90m# A tibble: 56,978 x 3[39m
##    height height_miles height_half_miles
##     [3m[90m&lt;dbl&gt;[39m[23m        [3m[90m&lt;dbl&gt;[39m[23m             [3m[90m&lt;dbl&gt;[39m[23m
## [90m 1[39m    700        0.133            0.066[4m3[24m
## [90m 2[39m      0        0                0     
## [90m 3[39m     [31mNA[39m       [31mNA[39m               [31mNA[39m     
## [90m 4[39m     [31mNA[39m       [31mNA[39m               [31mNA[39m     
## [90m 5[39m     [31mNA[39m       [31mNA[39m               [31mNA[39m     
## [90m 6[39m     [31mNA[39m       [31mNA[39m               [31mNA[39m     
## [90m 7[39m    600        0.114            0.056[4m8[24m
## [90m 8[39m     [31mNA[39m       [31mNA[39m               [31mNA[39m     
## [90m 9[39m     [31mNA[39m       [31mNA[39m               [31mNA[39m     
## [90m10[39m      0        0                0     
## [90m# … with 56,968 more rows[39m</code></pre>
<p>You’ll notice that the variables created have a lot of <code>NA</code>s - that’s because there are missing data. If you wanted to remove those, you could insert a <code>filter()</code> in the pipe chain:</p>
<pre class="r"><code>df %&gt;%
    filter(!is.na(height)) %&gt;%
    mutate(height_miles = height / 5280) %&gt;%
    select(height, height_miles)</code></pre>
<pre><code>## [90m# A tibble: 38,940 x 2[39m
##    height height_miles
##     [3m[90m&lt;dbl&gt;[39m[23m        [3m[90m&lt;dbl&gt;[39m[23m
## [90m 1[39m    700       0.133 
## [90m 2[39m      0       0     
## [90m 3[39m    600       0.114 
## [90m 4[39m      0       0     
## [90m 5[39m      0       0     
## [90m 6[39m      0       0     
## [90m 7[39m    500       0.094[4m7[24m
## [90m 8[39m    100       0.018[4m9[24m
## [90m 9[39m      0       0     
## [90m10[39m   [4m1[24m000       0.189 
## [90m# … with 38,930 more rows[39m</code></pre>
<p><code>is.na()</code> is a function that determines whether something is an <code>NA</code>. The <code>!</code> symbol negates the result, so we’re asking for every row where weight <em>is not</em> an <code>NA</code>.</p>
</div>
</div>
<div id="split-apply-combine" class="section level1">
<h1><span class="header-section-number">3</span> Split-apply-combine</h1>
<p>Many data analysis tasks can be approached using the <em>split-apply-combine</em> paradigm:</p>
<ol style="list-style-type: decimal">
<li>Split the data into groups</li>
<li>Apply some analysis to each group</li>
<li>Combine the results.</li>
</ol>
<p><code>dplyr</code> makes this very easy through the use of the <code>group_by()</code> function.</p>
<div id="the-group_by-function" class="section level2">
<h2><span class="header-section-number">3.1</span> The <code>group_by()</code> function</h2>
<p><img src="images/rstudio-cheatsheet-group_by.png" width="500" /></p>
<p>The <code>group_by()</code> function enables you to perform operations across groups within the data frame. It is typically used by inserting it in the “pipeline” before the desired group operation. For example, if we wanted to add a a new column that computed the mean height of reported wildlife impacts for each state, we could insert <code>group_by(state)</code> in the pipeline:</p>
<pre class="r"><code>df %&gt;%
    filter(!is.na(height)) %&gt;%
    group_by(state) %&gt;%          # Here we&#39;re grouping by state
    mutate(mean_height = mean(height)) %&gt;%
    select(state, mean_height)</code></pre>
<pre><code>## [90m# A tibble: 38,940 x 2[39m
## [90m# Groups:   state [59][39m
##    state mean_height
##    [3m[90m&lt;chr&gt;[39m[23m       [3m[90m&lt;dbl&gt;[39m[23m
## [90m 1[39m FL           892.
## [90m 2[39m IN           719.
## [90m 3[39m FL           892.
## [90m 4[39m FL           892.
## [90m 5[39m TX          [4m1[24m177.
## [90m 6[39m NY           937.
## [90m 7[39m N/A          994.
## [90m 8[39m N/A          994.
## [90m 9[39m MD          [4m1[24m265.
## [90m10[39m CA           989.
## [90m# … with 38,930 more rows[39m</code></pre>
<p>You’ll see that the same value for <code>mean_height</code> is reported for the same states (e.g. the mean height in Florida is 892 ft).</p>
</div>
<div id="the-summarize-function" class="section level2">
<h2><span class="header-section-number">3.2</span> The <code>summarize()</code> function</h2>
<p><img src="images/rstudio-cheatsheet-summarise.png" width="500" /></p>
<p>The <code>group_by()</code> function is often used together with <code>summarize()</code>, which collapses each group into a single-row summary of that group. For example, we collapse the result of the previous example by using <code>summarise()</code> instead of <code>mutate()</code>:</p>
<pre class="r"><code>df %&gt;%
    filter(!is.na(height)) %&gt;%
    group_by(state) %&gt;%
    summarise(mean_height = mean(height))</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## [90m# A tibble: 59 x 2[39m
##    state mean_height
##    [3m[90m&lt;chr&gt;[39m[23m       [3m[90m&lt;dbl&gt;[39m[23m
## [90m 1[39m AB           327.
## [90m 2[39m AK           334.
## [90m 3[39m AL           861.
## [90m 4[39m AR           968.
## [90m 5[39m AZ          [4m2[24m134.
## [90m 6[39m BC           497.
## [90m 7[39m CA           989.
## [90m 8[39m CO           442.
## [90m 9[39m CT           811.
## [90m10[39m DC           963.
## [90m# … with 49 more rows[39m</code></pre>
<p>You can also group by multiple columns - here let’s group by state and the airline:</p>
<pre class="r"><code>df %&gt;%
    filter(!is.na(height)) %&gt;%
    group_by(state, operator) %&gt;%
    summarise(mean_height = mean(height))</code></pre>
<pre><code>## `summarise()` regrouping output by &#39;state&#39; (override with `.groups` argument)</code></pre>
<pre><code>## [90m# A tibble: 213 x 3[39m
## [90m# Groups:   state [59][39m
##    state operator           mean_height
##    [3m[90m&lt;chr&gt;[39m[23m [3m[90m&lt;chr&gt;[39m[23m                    [3m[90m&lt;dbl&gt;[39m[23m
## [90m 1[39m AB    AMERICAN AIRLINES         318.
## [90m 2[39m AB    UNITED AIRLINES           350 
## [90m 3[39m AK    AMERICAN AIRLINES           0 
## [90m 4[39m AK    DELTA AIR LINES           414.
## [90m 5[39m AK    UNITED AIRLINES           311.
## [90m 6[39m AL    AMERICAN AIRLINES        [4m1[24m038.
## [90m 7[39m AL    DELTA AIR LINES           485.
## [90m 8[39m AL    SOUTHWEST AIRLINES       [4m1[24m020.
## [90m 9[39m AL    UNITED AIRLINES           375 
## [90m10[39m AR    AMERICAN AIRLINES         508.
## [90m# … with 203 more rows[39m</code></pre>
<p>Notice that in the above examples I’ve kept the early filter to drop <code>NA</code>s. This is important when performing summarizing functions like <code>mean()</code> or <code>sum()</code>. If <code>NA</code>s are present, the result will also be <code>NA</code>:</p>
<pre class="r"><code>df %&gt;%
    group_by(state) %&gt;%
    summarise(mean_height = mean(height))</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## [90m# A tibble: 59 x 2[39m
##    state mean_height
##    [3m[90m&lt;chr&gt;[39m[23m       [3m[90m&lt;dbl&gt;[39m[23m
## [90m 1[39m AB            [31mNA[39m 
## [90m 2[39m AK           334.
## [90m 3[39m AL            [31mNA[39m 
## [90m 4[39m AR            [31mNA[39m 
## [90m 5[39m AZ            [31mNA[39m 
## [90m 6[39m BC            [31mNA[39m 
## [90m 7[39m CA            [31mNA[39m 
## [90m 8[39m CO            [31mNA[39m 
## [90m 9[39m CT            [31mNA[39m 
## [90m10[39m DC            [31mNA[39m 
## [90m# … with 49 more rows[39m</code></pre>
<p>Once the data are grouped, you can also summarize multiple variables at the same time (and not necessarily on the same variable). For instance, you could add two more columns computing the minimum and maximum height:</p>
<pre class="r"><code>df %&gt;%
    filter(!is.na(height)) %&gt;%
    group_by(state, operator) %&gt;%
    summarise(mean_height = mean(height),
              min_height = min(height),
              max_height = max(height))</code></pre>
<pre><code>## `summarise()` regrouping output by &#39;state&#39; (override with `.groups` argument)</code></pre>
<pre><code>## [90m# A tibble: 213 x 5[39m
## [90m# Groups:   state [59][39m
##    state operator           mean_height min_height max_height
##    [3m[90m&lt;chr&gt;[39m[23m [3m[90m&lt;chr&gt;[39m[23m                    [3m[90m&lt;dbl&gt;[39m[23m      [3m[90m&lt;dbl&gt;[39m[23m      [3m[90m&lt;dbl&gt;[39m[23m
## [90m 1[39m AB    AMERICAN AIRLINES         318.          0       [4m1[24m300
## [90m 2[39m AB    UNITED AIRLINES           350           0       [4m1[24m400
## [90m 3[39m AK    AMERICAN AIRLINES           0           0          0
## [90m 4[39m AK    DELTA AIR LINES           414.          0       [4m1[24m700
## [90m 5[39m AK    UNITED AIRLINES           311.          0       [4m1[24m200
## [90m 6[39m AL    AMERICAN AIRLINES        [4m1[24m038.          0      [4m1[24m[4m1[24m300
## [90m 7[39m AL    DELTA AIR LINES           485.          0       [4m5[24m400
## [90m 8[39m AL    SOUTHWEST AIRLINES       [4m1[24m020.          0      [4m1[24m[4m0[24m000
## [90m 9[39m AL    UNITED AIRLINES           375           0       [4m2[24m800
## [90m10[39m AR    AMERICAN AIRLINES         508.          0       [4m3[24m400
## [90m# … with 203 more rows[39m</code></pre>
</div>
<div id="counting" class="section level2">
<h2><span class="header-section-number">3.3</span> Counting</h2>
<p>Often times you will want to know the number of observations found for each variable or combination of variables. One way to do this is to use the <code>group_by()</code> and <code>summarise()</code> functions in combination. For example, here is the number of observations for each aircraft engine type:</p>
<pre class="r"><code>df %&gt;%
    group_by(type_eng) %&gt;%
    summarise(count = n())</code></pre>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## [90m# A tibble: 5 x 2[39m
##   type_eng count
##   [3m[90m&lt;chr&gt;[39m[23m    [3m[90m&lt;int&gt;[39m[23m
## [90m1[39m A            2
## [90m2[39m C           34
## [90m3[39m D        [4m5[24m[4m6[24m705
## [90m4[39m F            3
## [90m5[39m [31mNA[39m         234</code></pre>
<p>Since this is such a common task, <code>dplyr</code> provides the <code>count()</code> function to do the same thing:</p>
<pre class="r"><code>df %&gt;%
    count(type_eng)</code></pre>
<pre><code>## [90m# A tibble: 5 x 2[39m
##   type_eng     n
##   [3m[90m&lt;chr&gt;[39m[23m    [3m[90m&lt;int&gt;[39m[23m
## [90m1[39m A            2
## [90m2[39m C           34
## [90m3[39m D        [4m5[24m[4m6[24m705
## [90m4[39m F            3
## [90m5[39m [31mNA[39m         234</code></pre>
<p>For convenience, <code>count()</code> also provides the <code>sort</code> argument:</p>
<pre class="r"><code>df %&gt;%
    count(type_eng, sort = TRUE)</code></pre>
<pre><code>## [90m# A tibble: 5 x 2[39m
##   type_eng     n
##   [3m[90m&lt;chr&gt;[39m[23m    [3m[90m&lt;int&gt;[39m[23m
## [90m1[39m D        [4m5[24m[4m6[24m705
## [90m2[39m [31mNA[39m         234
## [90m3[39m C           34
## [90m4[39m F            3
## [90m5[39m A            2</code></pre>
<p>You can also count the <em>combination of variables</em> by providing more than one column name to <code>count()</code>:</p>
<pre class="r"><code>df %&gt;%
    count(type_eng, num_engs, sort = TRUE)</code></pre>
<pre><code>## [90m# A tibble: 10 x 3[39m
##    type_eng num_engs     n
##    [3m[90m&lt;chr&gt;[39m[23m       [3m[90m&lt;dbl&gt;[39m[23m [3m[90m&lt;int&gt;[39m[23m
## [90m 1[39m D               2 [4m5[24m[4m3[24m652
## [90m 2[39m D               3  [4m2[24m753
## [90m 3[39m D               4   299
## [90m 4[39m [31mNA[39m             [31mNA[39m   232
## [90m 5[39m C               2    34
## [90m 6[39m F               2     3
## [90m 7[39m [31mNA[39m              2     2
## [90m 8[39m A               1     1
## [90m 9[39m A               2     1
## [90m10[39m D              [31mNA[39m     1</code></pre>
<p>Hmm, looks like most reported wildlife impacts involve planes with 2 D-type engines.</p>
</div>
</div>
<div id="exporting-data" class="section level1">
<h1><span class="header-section-number">4</span> Exporting data</h1>
<p>Now that you have learned how to use <code>dplyr</code> to extract information from or summarize your raw data, you may want to export these new data sets. Similar to the <code>read_csv()</code> function used for reading CSV files into R, there is a <code>write_csv()</code> function that generates CSV files from data frames.</p>
<p><strong>Important</strong>: Before using <code>write_csv()</code>, create a new folder called “data_output” and put it in your R Project folder. In general, you should never write generated datasets in the same directory as your raw data. The “data” folder should only contain the raw, unaltered data, and should be left alone to make sure we don’t delete or modify it.</p>
<p>Let’s save one of the summary data frames from the earlier examples where we computed the min, mean, and max heights of impacts by each state and airline:</p>
<pre class="r"><code>heightSummary &lt;- df %&gt;%
    filter(!is.na(height)) %&gt;%
    group_by(state, operator) %&gt;%
    summarise(mean_height = mean(height),
              min_height = min(height),
              max_height = max(height))</code></pre>
<pre><code>## `summarise()` regrouping output by &#39;state&#39; (override with `.groups` argument)</code></pre>
<p>Save the the new <code>heightSummary</code> data frame as a CSV file in your “data_output” folder:</p>
<pre class="r"><code>write_csv(heightSummary, path = file.path(&#39;data_output&#39;, &#39;heightSummary.csv&#39;)</code></pre>
<hr />
</div>
<div id="tips" class="section level1">
<h1><span class="header-section-number">5</span> Tips</h1>
<p>You will often need to create new variables based on a condition. To do this, you can use the <code>if_else()</code> function. Here’s the general syntax:</p>
<pre class="r"><code>if_else(&lt;condition&gt;, &lt;if TRUE&gt;, &lt;else&gt;)</code></pre>
<p>The first argument is a condition. If the condition is TRUE, then the value given to the second argument will be used; if not, then the third argument value will be used.</p>
<p>Here’s an example of creating a variable to determine which months in the wildlife impacts data are in the summer:</p>
<pre class="r"><code>df %&gt;%
    mutate(
        summer_month = if_else(incident_month %in% c(6, 7, 8), TRUE, FALSE))</code></pre>
<p>Of course, in this particular case the <code>if_else()</code> function isn’t even needed because the condition returns <code>TRUE</code> and <code>FALSE</code> values. However, if you wanted to extend this example to determine all four seasons, you could use a series of nested <code>if_else()</code> functions:</p>
<pre class="r"><code>df %&gt;%
    mutate(season =
        if_else(
            incident_month %in% c(3, 4, 5), &#39;Spring&#39;,
        if_else(
            incident_month %in% c(6, 7, 8), &#39;Summer&#39;,
        if_else(
            incident_month %in% c(9, 10, 11), &#39;Fall&#39;, &#39;Winter&#39;))))</code></pre>
<p>Note: The Base R version of this function is <code>ifelse()</code>, but I recommend using the <code>dplyr</code> version, <code>if_else()</code>, as it is a <a href="https://stackoverflow.com/questions/50646133/dplyr-if-else-vs-base-r-ifelse">stricter function</a>.</p>
<hr />
<p><strong>Page sources</strong>:</p>
<p>Some content on this page has been modified from other courses, including:</p>
<ul>
<li><a href="https://datacarpentry.org/R-ecology-lesson/">Data Analysis and Visualization in R for Ecologists</a>, by François Michonneau &amp; Auriel Fournier. Zenodo: <a href="http://doi.org/10.5281/zenodo.3264888" class="uri">http://doi.org/10.5281/zenodo.3264888</a></li>
<li>The amazing illustrations by <a href="https://github.com/allisonhorst">Allison Horst</a></li>
</ul>
</div>


<hr>

<div>
<center>
    EMSE 4574, Sec. 10: Programming for Analytics (Fall 2020)
    <br>
    <a href="https://www.gwu.edu/">George Washington University</a> |
    <a href="https://www.seas.gwu.edu/">School of Engineering & Applied Science</a>
    <br>
    <a href="https://www.jhelvy.com"><i class="fas fa-user"></i> Dr. John Paul Helveston</a> |
    <a href="mailto:jph@gwu.edu"><i class="fas fa-envelope"></i> jph@gwu.edu</a> |
    <i class="far fa-calendar-alt"></i> Mondays |
    <i class="far fa-clock"></i> 6:10–8:40 PM |
    <i class="fas fa-university"></i> Phillips Hall 108 |
    <a href="https://twitter.com/JohnHelveston"><i class="fab fa-twitter"></i></a> |
    <a href="https://github.com/emse-p4a-gwu/2020-Fall"><i class="fab fa-github"></i></a>
    <br>
    This work is licensed under a <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
    <br>
    See the <a href="LICENSE.html">licensing</a> page for more details about copyright information.
    <br>
    Content <i class="fab fa-creative-commons"></i> 2020 <a href="https://www.jhelvy.com">John Paul Helveston</a>
</center>
</div>

<!-- Add function to open links to external links in new tab, from: -->
<!-- https://yihui.name/en/2018/09/target-blank/ -->

<script src="js/external-link.js"></script>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = false;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
