---
title: "Getting Help"
output:
  html_document:
    number_sections: false
    toc: yes
---

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
rm(list=objects()) # start with a clean workspace
source("knitr_setup.R")
```

# Slack

All course communication will be managed through [Slack](https://emse-p4a-f20.slack.com). A link to sign up for the course slack page can be found on the one (and only) announcement on Blackboard.

**You can use Slack to**:

- Ask general questions.
- Ask for help with an assignment.
- Send direct, private messages to each other or the instructors (just like email...but better!)

**Asking for help on Slack**:

- When you have a question, post it in the most relevant channel (e.g. use `#hw01` for questions about homework 1).
- Be specific: if your code has an error you don't understand, **include the code and the error message** in your question.

Never heard of Slack? Watch this 2-minute video to see what it's all about:

<iframe width="560" height="315" src="https://www.youtube.com/embed/9RJZMSsH7-g" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

# Appointments w/Prof. Helveston

Rather than hold the same "Office Hours" every week, you can [use this app](https://jhelvy.appointlet.com/b/professor-helveston) to schedule a meeting with Prof. Helveston (also linked in the "Tools" menu above). This will automatically send a calendar invite with a link to a Webex video call.

If you and some classmates want to meet together, have one person schedule the meeting and type in the names of everyone else in the scheduling form.

This can be a difficult class - **do not suffer in silence!** Come talk with me!

# Tutoring hours

Your class tutors will each hold a specific period of time each week dedicated to help you will course assignments. Please don't make your tutors sit and do emails for two hours - come by and ask for help!

# GW Coders

[GW Coders](http://gwcoders.github.io/) is a study group that brings together students and faculty to apply computational and data analytics skills in research. It can be another great community to get extra help and expand your coding skills beyond what is covered in this class. Regular weekly meetings are usually held on Fridays - check their [events](https://gwcoders.github.io/studyGroup/#events) page for details.

# Library Services

While the University Library is not a stand in for TAs, you can schedule a consultation for general help with Coding, Programming, Data, Statistical, and GIS. See more at https://academiccommons.gwu.edu/writing-research-help
